spring:
  application:
    name: quickpoll
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/quickpoll}
    username: ${DB_USERNAME:basit}
    password: ${DB_PASSWORD:bece2018}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      continue-on-error: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:Z29vZC1zZWNyZXQta2V5bG9uZ3NlY3JldGtleXRoYXRzaG91bGRiZXJlcGxhY2Vkd2l0aGVudnZhcmlhYmxl}
  expiration: 86400000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
